In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\narla\Downloads\Healthcare project\hospital_readmissions.csv")

df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [2]:
df.columns = df.columns.str.lower().str.strip()

In [3]:
df['readmitted_flag'] = df['readmitted'].map({'yes': 1, 'no': 0})

In [4]:
def convert_age(age):
    age = age.strip('[]()')
    lower = int(age.split('-')[0])
    upper = int(age.split('-')[1])
    return (lower + upper) / 2

df['age_numeric'] = df['age'].apply(convert_age)

In [5]:
df['medical_specialty'] = df['medical_specialty'].replace("Missing", np.nan)

In [6]:
df['total_visits'] = df['n_outpatient'] + df['n_inpatient'] + df['n_emergency']

In [7]:
df['high_utilization_flag'] = (
    df['total_visits'] > df['total_visits'].quantile(0.75)
).astype(int)

In [8]:
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,...,diag_3,glucose_test,a1ctest,change,diabetes_med,readmitted,readmitted_flag,age_numeric,total_visits,high_utilization_flag
0,[70-80),8,72,1,18,2,0,0,NaN,Circulatory,...,Other,no,no,no,yes,no,0,75.0,2,0
1,[70-80),3,34,2,13,0,0,0,Other,Other,...,Other,no,no,no,yes,no,0,75.0,0,0
2,[50-60),5,45,0,18,0,0,0,NaN,Circulatory,...,Circulatory,no,no,yes,yes,yes,1,55.0,0,0
3,[70-80),2,36,0,12,1,0,0,NaN,Circulatory,...,Diabetes,no,no,yes,yes,yes,1,75.0,1,0
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,...,Respiratory,no,no,no,yes,no,0,65.0,0,0

In [9]:
output_path = r"C:\Users\narla\Downloads\Healthcare project\clean_healthcare_data.csv"

df.to_csv(output_path, index=False)

print("File saved successfully.")

File saved successfully.